spring:
  banner:
    location: classpath:resources/banner.txt
  messages:
    basename: resources.lang.labels
application:
  rightAnswerCount: 3
  enResource: classpath:data/enTestQuestionsWithAnswers.csv
  ruResource: classpath:data/ruTestQuestionsWithAnswers.csv
  locale: en