spring:
  banner:
    location: classpath:resources/banner.txt
  messages:
    basename: resources.lang.labels
application:
  template: data/%sTestQuestionsWithAnswers.csv
  rightAnswerCount: 3
  locale: en
